### ISSUE TITLE
VS showing '00oo' instead of dashes

### ISSUE THREAD

**Issue by Jak-Kav** [Jak-Kav/A3xx-LCD-Devices#1]
Issue raised with the MobiFlight config for the FBW A320 where it will sometimes show '00oo' instead of '- - - - -'.
This is definatley a config issue, and needs some of the rules/logic adjusting.

LOW PRIORITY

**Comment by ZockerParadise** [comment]
On the V/S Part ..  when below -900  (the - change to +) and shows (ex. +1000 instead of -1000.

On Fenix and FBW

**Comment by Jak-Kav** [comment]
Fixed in latest commit to config
