### ISSUE TITLE
Unhandled exception - can't upload .mfmc file

### ISSUE THREAD

**Issue by mrb13676** [Jak-Kav/A3xx-LCD-Devices#3]
Getting an unhandled exception when uploading the mfmc file. Reports error in XML document (8, 2).
Any ideas?

**Comment by Jak-Kav** [comment]
Hi there,
Could you provide some more details to help me try and troubleshoot this please?
Screenshots & version numbers would be helpful too please :-)

**Comment by mrb13676** [comment]
Sure.... Mobiflight 9.7.1
The .mfmc file is MobiFlight_Mega_Kav_1FCI_2EFIS.mfmc (from the repository here)
Output from the error in the text file and screenshot attached..

The error is thrown when the .mfmc file is selected in the file dialog when clicking on "open"

[mobiflighterror.txt](https://github.com/Jak-Kav/A3xx-LCD-Devices/files/12300788/mobiflighterror.txt)
![Screenshot 2023-08-09 114457](https://github.com/Jak-Kav/A3xx-LCD-Devices/assets/24562721/8132616f-6a2d-4f69-9352-a39c3d4c4b90)

**Comment by Jak-Kav** [comment]
Thank you.
I will take a look into this and get back to you once I've had a chance.

**Comment by Jak-Kav** [comment]
I've had a look myself and spoke with one of the MF code contributors.
It's definatley a messed up file which was either corrupted when downloaded, or the `raw` file wasn't downloaded.

When viewing the file (https://github.com/Jak-Kav/A3xx-LCD-Devices/blob/main/FCU%26EFIS/MobiFlight/MobiFlight_Mega_Kav_1FCU_2EFIS.mfmc) make sure you either right click `RAW` and save file as, or click the `RAW` and use that link to download the actual file using a web downloader, etc.

If the problem still persists after trying this, let me know :-)

**Comment by mrb13676** [comment]
Thanks. So I cut and pasted the RAW into Notepad++ and saved it and was able to successfully load. The original file came from the github downloader so not sure where the corruption came from but it seems to be fine now. Thanks so much!

**Comment by Jak-Kav** [comment]
Perfect, thanks again :-)
