### ISSUE TITLE
Add a link to the webstore :-)

### ISSUE THREAD

**Issue by tigert** [Jak-Kav/A3xx-LCD-Devices#4]
Hey, was looking for the link for the store, and found this on my browser history instead. Could perhaps add a link to the README of all related git repos (firmware source etc) to point the random wanderer like me towards the webstore to buy a set :-)

**Comment by Jak-Kav** [comment]
I do have a website link on the right of each repo, but sure, I'll look at adding direct links to the readme. Thanks :-)

**Comment by tigert** [comment]
oh, I must have been blind then :-) (Edit: oh duh, indeed! But I guess it wouldnt hurt on the README either)
