### ISSUE TITLE
Toliss with XPlane(Direct) without FSUIPC

### ISSUE THREAD

**Issue by srobert72** [Jak-Kav/A3xx-LCD-Devices#5]
Hello,

Could it be possible to have a Mobiflight configuration version for XPlane Toliss using direct XPlane(Direct) and without FSUIPC ?

Thank you in advance
Regards
Stephane

**Comment by bdpd1** [comment]
I’m working on a config now now with the Kav custom 2.4.x firmware that’s set up for the dual EFIS and FCU.  I had the datarefs pretty correct for the FCU part and am working on the EFIS now (ie toliss does not support QFE).  I’ll share on discord once I am able to test it fully.

**Comment by srobert72** [comment]
I managed to do something with this file (extension *.mcc instead of *.txt).
I just change sources to XplaneDataRef instead of FSUIPC using same path that in XPUIPCOffsets.cfg file.
It works on XPlane12.

[Test2.txt](https://github.com/Jak-Kav/A3xx-LCD-Devices/files/13062742/Test2.txt)

**Comment by Jak-Kav** [comment]
Hi there :-)
I'm glad to see this is being developed by the community. Can I ask that it is continued in the Discord though please?
As this is for active bugs/issues in the code. Whereas what we're talking about here is a more of a feature request.

If people come up with a working config, I'll be sure to add it to the repo with a credit of course.
Have a great weekend!
