### ISSUE TITLE
Numerical difference for HDG value

### ISSUE THREAD

**Issue by srobert72** [Jak-Kav/A3xx-LCD-Devices#6]
Hello,

I use Xplane12 + TolissA319.
There is a difference between HDG in XPlane and on my KAV Display : 219 instead of 216.
Always a difference of 3 when I change HDG in cockpit.

Using DatarefTools I found the same difference.
In your configuration you use sim/cockpit/autopilot/heading = 219
But there is sim/cockpit/autopilot/heading_mag = 216.
I think **sim/cockpit/autopilot/heading_mag** is the right dataref to use.

Regards
Stéphane

**Comment by Jak-Kav** [comment]
This change has been implemented.
